# Environment Settings
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=false

# Project Settings
# Your modId must be only lowercase letters, numbers, and _ or - symbols only
modDisplayName=SmartBrainLib
modId=smartbrainlib
group=net.tslat

# Project Properties
modLicense=MPL-2.0
modAuthors=Tslat
modDescription=A library mod for smarter Brains and easier usage of the Brain system.

# Links
modHomepage=https://www.curseforge.com/minecraft/mc-mods/smartbrainlib
modGitRepo=https://github.com/Tslat/SmartBrainLib
modIssuesTracker=https://github.com/Tslat/SmartBrainLib/issues

# Publishing
modrinthProjectId=PuyPazRT
curseforgeProjectId=661293